// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/classroom/[courseId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/classroom/[courseId]">> = Specific
  const handler = {} as typeof import("../../src/app/classroom/[courseId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/chapters/[chapterId]/materials/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/chapters/[chapterId]/materials">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/chapters/[chapterId]/materials/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/chapters/[chapterId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/chapters/[chapterId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/chapters/[chapterId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/courses/[courseId]/chapters/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/courses/[courseId]/chapters">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/courses/[courseId]/chapters/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/enrollments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/enrollments">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/enrollments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/materials/[materialId]/assignment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/materials/[materialId]/assignment">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/materials/[materialId]/assignment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/materials/[materialId]/quiz/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/materials/[materialId]/quiz">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/materials/[materialId]/quiz/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/materials/[materialId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/materials/[materialId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/materials/[materialId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/media/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/media/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/media/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assignments/[assignmentId]/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assignments/[assignmentId]/submit">> = Specific
  const handler = {} as typeof import("../../src/app/api/assignments/[assignmentId]/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/google/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/google/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/google/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/google/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/google/start">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/google/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/certificates/[courseId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/certificates/[courseId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/certificates/[courseId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/courses/[courseId]/enroll/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/courses/[courseId]/enroll">> = Specific
  const handler = {} as typeof import("../../src/app/api/courses/[courseId]/enroll/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/courses/[courseId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/courses/[courseId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/courses/[courseId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/courses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/courses">> = Specific
  const handler = {} as typeof import("../../src/app/api/courses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/learning/[courseId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/learning/[courseId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/learning/[courseId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/materials/[materialId]/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/materials/[materialId]/complete">> = Specific
  const handler = {} as typeof import("../../src/app/api/materials/[materialId]/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/my/courses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/my/courses">> = Specific
  const handler = {} as typeof import("../../src/app/api/my/courses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quizzes/[quizId]/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quizzes/[quizId]/submit">> = Specific
  const handler = {} as typeof import("../../src/app/api/quizzes/[quizId]/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/setup/bootstrap/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/setup/bootstrap">> = Specific
  const handler = {} as typeof import("../../src/app/api/setup/bootstrap/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
