// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/classroom/[courseId]" | "/dashboard" | "/login" | "/register"
type AppRouteHandlerRoutes = "/api/admin/analytics" | "/api/admin/chapters/[chapterId]" | "/api/admin/chapters/[chapterId]/materials" | "/api/admin/courses/[courseId]/chapters" | "/api/admin/enrollments" | "/api/admin/materials/[materialId]" | "/api/admin/materials/[materialId]/assignment" | "/api/admin/materials/[materialId]/quiz" | "/api/admin/media/upload" | "/api/assignments/[assignmentId]/submit" | "/api/auth/google/callback" | "/api/auth/google/start" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/register" | "/api/certificates/[courseId]" | "/api/courses" | "/api/courses/[courseId]" | "/api/courses/[courseId]/enroll" | "/api/learning/[courseId]" | "/api/materials/[materialId]/complete" | "/api/me" | "/api/my/courses" | "/api/quizzes/[quizId]/submit" | "/api/setup/bootstrap"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/api/admin/analytics": {}
  "/api/admin/chapters/[chapterId]": { "chapterId": string; }
  "/api/admin/chapters/[chapterId]/materials": { "chapterId": string; }
  "/api/admin/courses/[courseId]/chapters": { "courseId": string; }
  "/api/admin/enrollments": {}
  "/api/admin/materials/[materialId]": { "materialId": string; }
  "/api/admin/materials/[materialId]/assignment": { "materialId": string; }
  "/api/admin/materials/[materialId]/quiz": { "materialId": string; }
  "/api/admin/media/upload": {}
  "/api/assignments/[assignmentId]/submit": { "assignmentId": string; }
  "/api/auth/google/callback": {}
  "/api/auth/google/start": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/register": {}
  "/api/certificates/[courseId]": { "courseId": string; }
  "/api/courses": {}
  "/api/courses/[courseId]": { "courseId": string; }
  "/api/courses/[courseId]/enroll": { "courseId": string; }
  "/api/learning/[courseId]": { "courseId": string; }
  "/api/materials/[materialId]/complete": { "materialId": string; }
  "/api/me": {}
  "/api/my/courses": {}
  "/api/quizzes/[quizId]/submit": { "quizId": string; }
  "/api/setup/bootstrap": {}
  "/classroom/[courseId]": { "courseId": string; }
  "/dashboard": {}
  "/login": {}
  "/register": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
